name: BlueSalt Labs (Luke Sontrop)
title: BlueSalt Labs Home
description: >
  The BlueSalt Labs home page. Read the BlueSalt Labs blog
  and learn more about current projects. 
baseurl: /
email: luke@bluesaltlabs.com
twitter_username: bluesaltlabs
github_username:  bluesalt-labs
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
url: "http://www.bluesaltlabs.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:title
collections:
  projects:
    output: true
    permalink: /:collection/:name

#title: Your awesome title

#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog

#twitter_username: jekyllrb
#github_username:  jekyll

## Build settings
#markdown: kramdown
#theme: minima
#gems:
#  - jekyll-feed
#exclude:
#  - Gemfile
#  - Gemfile.lock

